project:
  type: website

website:
  title: "Compilation analyses statistiques"
  navbar:
    left:
      - href: index.qmd
        text: Introduction
      - statistiques_descriptives.qmd
      - analyses_factorielles.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



