project:
  type: website
  output-dir: docs

website:
  title: "Statistiques"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - statistiques_descriptives.qmd
      - stat_inf.qmd
      - analyses_factorielles.qmd
      - classification_NS.qmd
      - regression_linéaire.qmd
      - regression_logistique.qmd
      - données_manquantes.qmd
      - redressement.qmd
      - web_scraping.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



