project:
  type: website
  output-dir: docs

website:
  title: "Site_quarto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - statistiques_descriptives.qmd
      - analyses_factorielles.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



